### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by avalynndev** [codeblitz97/elyzen#2]
- [x] decrease the size of the episodes image as shown in the video, and proper image height and width
- [x] add a better README
- [x] Group episodes by 100
- [x] add footer
- [x] add policy, dmca and terms
- [x] add navbar and increase the width of the sidebar.
- [x] add the following data to INFO: Type, Episodes, Genres, Aired, Status, Season, Country, Studios, Source, Duration, Popularity
- [x] add a sexy looking search bar.
- [x] better episode layout
- [x] better sidebar
- [x] add beautiful modal showing changes
- [x] add continue watching
- [x] Add a button to watch trailer
- [x] add upcoming anime
- [x] SEO - 100%
- [ ] add recommendation anime
- [ ] add relations in chronological order, characters when hovered shows the original person
- [ ] option to change between japanese and english
- [ ] anilst login and sync
- [x] PWA
- [ ] Accessibility
- [ ] Best Practices
- [ ] Performance
[lighthouse report.zip](https://github.com/user-attachments/files/15542547/lighthouse.report.zip)

**Comment by avalynndev** [comment]
https://github.com/codeblitz97/elyzen/assets/100826194/1ab16ade-cf92-41c5-a2e3-23c86837a9db

**Comment by avalynndev** [comment]
@codeblitz97

**Comment by sulvii** [comment]
First priority is layout change of episodes list and then search bar

**Comment by avalynndev** [comment]
continue watching ain't working properly fix @codeblitz97

**Comment by sulvii** [comment]
What's the issue exactly

**Comment by avalynndev** [comment]
> What's the issue exactly

Well it stores the continue watching in local storage perfectly, however when i click on the button to open that episode, the episode plays from the start instead of continuing from where i left it.

**Comment by sulvii** [comment]
@avalynndev it works perfectly fine for me. I declare it as done

**Comment by avalynndev** [comment]
@codeblitz97, then i recommend u remove that timestamp on the continue watching card to not create confusion..

**Comment by avalynndev** [comment]
```html
<p className='mt-2 text-sm text-gray-600 dark:text-gray-400'> {parseTime(episode.duration)} </p>
``` 
will be recommended

**Comment by sulvii** [comment]
This is an issue with the parseTime function

**Comment by sulvii** [comment]
Okay it should fix now, for some reason it was adding +3 seconds

**Comment by sulvii** [comment]
Watch trailer button is added in the settings

**Comment by avalynndev** [comment]
> Watch trailer button is added in the settings

bros cooking fr

**Comment by avalynndev** [comment]
@codeblitz97 i added lighthouse report, check it..

**Comment by sulvii** [comment]
@avalynndev do the lighthouse report on this domain: elyzen-app-f421b6774ebb.herokuapp.com

**Comment by avalynndev** [comment]
sure

**Comment by avalynndev** [comment]
@codeblitz97, the website has a error
```
Application error
An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command
heroku logs --tail
```

**Comment by sulvii** [comment]
Both vercel and heruko build is giving the same error. I always test in production so it shouldn't work like this

![image](https://github.com/codeblitz97/elyzen/assets/94981761/b7d92aef-10d1-42e5-8965-99cdb3527e69)

**Comment by sulvii** [comment]
Probably because of some issues anyways, I'm gonna rebuild the full site with anilist's UI

**Comment by avalynndev** [comment]
😭 sed life for you

**Comment by avalynndev** [comment]
nice website ui

**Comment by Azmarine13** [comment]
**I like your website UI Design 👍** 

Would be interested to also see: _SIMKL Login & Sync feature as well_

- API Documentation: https://simkl.docs.apiary.io/#reference/sync 
- Anime Page: https://simkl.com/anime/

**Comment by sulvii** [comment]
Yes I will be adding Anilist, and SIMKL soon
