### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by sulvii** [codeblitz97/elyzen#35]
## Roadmap for Elyzen

- [x] All Time Popular Movies
- [x] Character information page (with full information)
- [ ] Proper AniList and SIMKL sync
- [ ] Studio Information page
- [ ] Staff/Voice Actors page
- [ ] Anime search by character name
